In [ ]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('R:/PROJECTS/User Journey Funnel Analysis/user_journey_funnel_analysis/retail_user_behavior_100k/retail_user_behavior_100k.csv')
print('\nDataset Overview:\n')
df

Dataset Overview:

,session_id,user_id,timestamp_utc,event_index,user_action,product_id,category,brand,price,channel,device_type,region,traffic_source,time_spent_sec,session_length,interaction_count,is_conversion,drop_off_flag
0,S0000001,U000372,2026-01-08T02:34:40Z,1,view,P1481,Electronics,Samsung,316.55,mobile,desktop,JP,organic,25,4,1,0,0
1,S0000001,U000372,2026-01-08T02:35:20Z,2,wishlist,P1481,Electronics,Samsung,316.55,mobile,desktop,JP,organic,28,4,2,0,0
2,S0000001,U000372,2026-01-08T02:35:43Z,3,view,P1481,Electronics,Samsung,316.55,mobile,desktop,JP,organic,5,4,3,0,0
3,S0000001,U000372,2026-01-08T02:36:13Z,4,drop,P1481,Electronics,Samsung,316.55,mobile,desktop,JP,organic,16,4,4,0,1
4,S0000002,U004812,2026-01-29T11:07:27Z,1,view,P1836,Groceries,OrganicCo,212.37,mobile,tablet,UK,direct,15,4,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108579,S0018000,U002836,2026-02-20T14:20:30Z,3,view,P1821,Groceries,DailyFresh,402.41,app,android,DE,referral,24,7,3,0,0
108580,S0018000,U002836,2026-02-20T14:21:15Z,4,click,P1821,Groceries,DailyFresh,402.41,app,android,DE,referral,26,7,4,0,0
108581,S0018000,U002836,2026-02-20T14:21:52Z,5,add_to_cart,P1821,Groceries,DailyFresh,402.41,app,android,DE,referral,20,7,5,0,0
108582,S0018000,U002836,2026-02-20T14:22:24Z,6,click,P1821,Groceries,DailyFresh,402.41,app,android,DE,referral,17,7,6,0,0
108583,S0018000,U002836,2026-02-20T14:22:49Z,7,drop,P1821,Groceries,DailyFresh,402.41,app,android,DE,referral,24,7,7,0,1

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 108584 entries, 0 to 108583
Data columns (total 18 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   session_id         108584 non-null  str
 1   user_id            108584 non-null  str
 2   timestamp_utc      108584 non-null  str
 3   event_index        108584 non-null  int64
 4   user_action        108584 non-null  str
 5   product_id         108584 non-null  str
 6   category           108584 non-null  str
 7   brand              108584 non-null  str
 8   price              108584 non-null  float64
 9   channel            108584 non-null  str
 10  device_type        108584 non-null  str
 11  region             108584 non-null  str
 12  traffic_source     108584 non-null  str
 13  time_spent_sec     108584 non-null  int64
 14  session_length     108584 non-null  int64
 15  interaction_count  108584 non-null  int64
 16  is_conversion      108584 non-null  int64
 17  drop_off_flag      108584 non-null  int64
dtypes: float64(1), int64(6), str(11)
memory usage: 23.0 MB

In [4]:
print('Number of null values:')
df.isna().sum()

Number of null values:

session_id           0
user_id              0
timestamp_utc        0
event_index          0
user_action          0
product_id           0
category             0
brand                0
price                0
channel              0
device_type          0
region               0
traffic_source       0
time_spent_sec       0
session_length       0
interaction_count    0
is_conversion        0
drop_off_flag        0
dtype: int64

In [5]:
print('Number of duplicate rows:')
df.duplicated().sum()

Number of duplicate rows:

np.int64(0)

In [6]:
print('Number of unique values:')
df.nunique()

Number of unique values:

session_id            18000
user_id                6806
timestamp_utc        108020
event_index              13
user_action               6
product_id             1200
category                  8
brand                    33
price                  1189
channel                   3
device_type               4
region                    9
traffic_source            7
time_spent_sec           56
session_length           11
interaction_count        13
is_conversion             2
drop_off_flag             2
dtype: int64

In [7]:
df['timestamp_utc'] = pd.to_datetime(df['timestamp_utc'])
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 108584 entries, 0 to 108583
Data columns (total 18 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   session_id         108584 non-null  str
 1   user_id            108584 non-null  str
 2   timestamp_utc      108584 non-null  datetime64[us, UTC]
 3   event_index        108584 non-null  int64
 4   user_action        108584 non-null  str
 5   product_id         108584 non-null  str
 6   category           108584 non-null  str
 7   brand              108584 non-null  str
 8   price              108584 non-null  float64
 9   channel            108584 non-null  str
 10  device_type        108584 non-null  str
 11  region             108584 non-null  str
 12  traffic_source     108584 non-null  str
 13  time_spent_sec     108584 non-null  int64
 14  session_length     108584 non-null  int64
 15  interaction_count  108584 non-null  int64
 16  is_conversion      108584 non-null  int64
 17  drop_off_flag      108584 non-null  int64
dtypes: datetime64[us, UTC](1), float64(1), int64(6), str(10)
memory usage: 21.0 MB

In [15]:
print(f'Date Range:\nFrom {df['timestamp_utc'].min()} To {df['timestamp_utc'].max()}')

Date Range:
From 2026-01-01 08:15:17+00:00 To 2026-05-01 07:57:37+00:00

In [8]:
df['user_action'].value_counts()

user_action
view           44245
click          27735
drop           13797
add_to_cart    11642
wishlist        6962
purchase        4203
Name: count, dtype: int64

In [9]:
new_df = df[df['user_action'].isin(
    ['view', 'click', 'wishlist', 'add_to_cart', 'purchase']
)]

In [10]:
new_df['event_sequence'] = df.groupby('session_id').cumcount() +1
new_df

,session_id,user_id,timestamp_utc,event_index,user_action,product_id,category,brand,price,channel,device_type,region,traffic_source,time_spent_sec,session_length,interaction_count,is_conversion,drop_off_flag,event_sequence
0,S0000001,U000372,2026-01-08 02:34:40+00:00,1,view,P1481,Electronics,Samsung,316.55,mobile,desktop,JP,organic,25,4,1,0,0,1
1,S0000001,U000372,2026-01-08 02:35:20+00:00,2,wishlist,P1481,Electronics,Samsung,316.55,mobile,desktop,JP,organic,28,4,2,0,0,2
2,S0000001,U000372,2026-01-08 02:35:43+00:00,3,view,P1481,Electronics,Samsung,316.55,mobile,desktop,JP,organic,5,4,3,0,0,3
4,S0000002,U004812,2026-01-29 11:07:27+00:00,1,view,P1836,Groceries,OrganicCo,212.37,mobile,tablet,UK,direct,15,4,1,0,0,1
5,S0000002,U004812,2026-01-29 11:07:40+00:00,2,add_to_cart,P1836,Groceries,OrganicCo,212.37,mobile,tablet,UK,direct,6,4,2,0,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108578,S0018000,U002836,2026-02-20 14:19:59+00:00,2,wishlist,P1821,Groceries,DailyFresh,402.41,app,android,DE,referral,20,7,2,0,0,2
108579,S0018000,U002836,2026-02-20 14:20:30+00:00,3,view,P1821,Groceries,DailyFresh,402.41,app,android,DE,referral,24,7,3,0,0,3
108580,S0018000,U002836,2026-02-20 14:21:15+00:00,4,click,P1821,Groceries,DailyFresh,402.41,app,android,DE,referral,26,7,4,0,0,4
108581,S0018000,U002836,2026-02-20 14:21:52+00:00,5,add_to_cart,P1821,Groceries,DailyFresh,402.41,app,android,DE,referral,20,7,5,0,0,5
108582,S0018000,U002836,2026-02-20 14:22:24+00:00,6,click,P1821,Groceries,DailyFresh,402.41,app,android,DE,referral,17,7,6,0,0,6

In [19]:
new_df['category'].value_counts()

category
Groceries      12099
Accessories    11979
Shoes          11974
Sports         11955
Apparel        11839
Home           11808
Electronics    11664
Beauty         11469
Name: count, dtype: int64

In [23]:
print(f'Number of unique brands: {new_df['brand'].nunique()}')
new_df['brand'].value_counts()

Number of unique brands: 33

brand
Nike            9825
Adidas          8097
Puma            6137
Target          3283
Bose            3150
Ray-Ban         3097
Wilson          3019
Neutrogena      2752
OrganicCo       2749
DailyFresh      2626
Fitbit          2568
Coach           2545
H&M             2511
Under Armour    2419
Spalding        2356
Asics           2339
GreatValue      2324
Loreal          2294
Mainstays       2270
Samsung         2269
Dove            2244
FreshFarm       2200
NatureBest      2200
Wayfair         2196
Ikea            2174
Olay            2102
Maybelline      2077
Decathlon       2070
Apple           2038
HomeGoods       1885
New Balance     1808
Sony            1639
Fossil          1524
Name: count, dtype: int64

In [27]:
new_df.groupby('brand')['price'].sum()

brand
Adidas          1835300.62
Apple            455677.78
Asics            632633.92
Bose             945222.24
Coach            571635.14
DailyFresh       674064.93
Decathlon        568939.63
Dove             539569.54
Fitbit           650485.47
Fossil           433862.16
FreshFarm        575481.36
GreatValue       572047.70
H&M              560886.29
HomeGoods        453663.38
Ikea             478381.93
Loreal           525581.61
Mainstays        704070.21
Maybelline       493923.50
NatureBest       574575.07
Neutrogena       690167.50
New Balance      414353.42
Nike            2720838.90
Olay             425255.95
OrganicCo        501039.79
Puma            1489866.15
Ray-Ban          695351.92
Samsung          661665.75
Sony             369499.06
Spalding         721596.51
Target           769657.48
Under Armour     667972.14
Wayfair          537048.66
Wilson           757128.42
Name: price, dtype: float64